services:
  - type: web
    name: eartheye
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
